# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('score', models.IntegerField(max_length=10)),
                ('viewcount', models.IntegerField(max_length=10)),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
