# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=1, null=True)),
                ('viewcount', models.IntegerField(default=1, null=True)),
                ('tags', models.CharField(max_length=100, null=True)),
                ('creationdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
