# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
        migrations.RemoveField(
            model_name='post',
            name='viewcount',
        ),
    ]
