# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
        migrations.AddField(
            model_name='post',
            name='values',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
