# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
