# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 16:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180405_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='FebJson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MarJson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='NewTags',
        ),
    ]
