# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 17:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180411_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanJson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
