# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jancsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jancsv',
            name='score',
            field=models.IntegerField(),
        ),
    ]
